### ISSUE TITLE
Dark Mode GUI support

### ISSUE THREAD

**Issue by Balakay420** [ReillyGregorio/ProbablyChests#20]
Please add support for https://www.curseforge.com/minecraft/texture-packs/default-dark-mode

**Comment by ArcanePigeon** [comment]
My mod currently uses the LibGui library to generate the custom chest UI dynamically so that is not possible. I have been unable to find a good program to generate the UI sprite for me, so until I find something that works, support for dark mode is not possible. It would be theoretically possible to use a datapack to modify the color values in LibGui but I do not know how to do that and do not plan on making a datapack.
